export const PROGRAMS = [
  {
    slug: '/computacion-e-informatica',
    title: 'COMPUTACIÓN E INFORMÁTICA',
    imgFront: 'Programs/Front/FrontComputacion.webp',
    altImgFront: 'Imagen de descripción de la carrera de Computación e Informática',
    descriptionShort: 'La carrera de Computación e Informática se centra en sistemas, desarrollo de software, redes y seguridad. Los estudiantes adquieren habilidades en programación, bases de datos y administración de sistemas, preparándolos para roles en tecnología de la información.',
    about: '¿QUÉ ES COMPUTACIÓN E INFORMÁTICA?',
    descriptionAbout1: 'La computación e informática son la ciencia y práctica de procesar, almacenar y comunicar información con computadoras. Incluyen diseño, construcción e implementación de sistemas informáticos, y el estudio de cómo humanos y máquinas procesan información.',
    descriptionAbout2: 'Temas incluyen algoritmos, programación, arquitectura de computadoras, sistemas operativos, redes, inteligencia artificial, aprendizaje automático y seguridad. Son fundamentales en la vida moderna, desde comunicación hasta investigación científica, y siguen evolucionando rápidamente.',
    imgAbout: 'Programs/About/ComputacionAbout.webp',
    altImgAbout: '¿Qué es computación e informática?',
    functions: '¿QUÉ ES LO QUE HACE UN TÉCNICO EN COMPUTACIÓN E INFORMÁTICA?',
    descriptionfunctions1: 'Un profesional en el campo de la Computación e Informática crea software en diferentes plataformas con herramientas tecnológicas apropiadas, garantizando la calidad según estándares actuales. También colabora en la planificación y diseño de soluciones informáticas, priorizando las necesidades del cliente.',
    descriptionfunctions2: 'Un técnico en Computación e Informática realiza tareas como mantenimiento de sistemas, diagnóstico de problemas, instalación de software, configuración de redes, soporte técnico a usuarios, desarrollo de aplicaciones simples y asistencia en la implementación de soluciones informáticas.',
    laborFieldDescription: 'egresado en Computación e Informática',
    laborFieldItems: [
      ['Ciberseguridad:', ' Especialista en Ciberseguridad'],
      ['Desarrollador y programador web:', ' Desarrollador Web'],
      ['Empresa de electrónicos y software:', ' Ingeniero de Software'],
      ['Soporte técnico e informático:', ' Técnico de Soporte Informático'],
      ['Consultoría en tecnología:', ' Consultor de Tecnología'],
      ['Industria de videojuegos:', ' Tester de Videojuegos']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN COMPUTACIÓN E INFORMÁTICA?',
    syllabusDescription1: 'La Computación e Informática es una carrera que estudia la teoría, el diseño, la implementación y la gestión de sistemas informáticos, así como la creación y el mantenimiento de software y aplicaciones. Se abarcan temas como programación, algoritmia, estructuras de datos, arquitectura de computadoras, sistemas operativos, redes, inteligencia artificial, ciberseguridad y bases de datos, entre otros.',
    syllabusDescription2: 'El objetivo es formar profesionales capaces de desarrollar soluciones informáticas eficientes y efectivas, adaptadas a las necesidades de los usuarios y las organizaciones, con un enfoque en la calidad, la innovación y la ética.',
    imgSyllabus: 'Programs/Syllabus/SyllabusComputacion.webp',
    altImgSyllabus: '¿Qué se estudia en computación e Informática?',
    cycle1: [
      'Organización y administración del soporte técnico',
      'Integración de las TICS',
      'Mantenimiento de equipos de cómputo',
      'Diseño de redes de comunicación',
      'Seguridad informática',
      'Técnicas de comunicación',
      'Lógica y funciones',
      'Cultura física y deporte'
    ],
    cycle2: [
      'Informática e internet',
      'Reparación de equipos de cómputo',
      'Instalación y configuración de redes de comunicación',
      'Herramientas de gestión de redes de comunicación',
      'Administración de redes',
      'Software de servidor de red',
      'Ofimática',
      'Fundamentos de investigación'
    ],
    cycle3: [
      'Análisis y diseño de sistemas',
      'Herramientas de desarrollo de software',
      'Taller de base de datos',
      'Lógica de programación',
      'Taller de modelamiento de software',
      'Sociedad y Economía en la Globalización',
      'Medio Ambiente y Desarrollo Sostenible',
      'Investigación e Innovación tecnológicas'
    ],
    cycle4: [
      'Taller de programación distribuida',
      'Metodologías de desarrollo de Software',
      'Taller de programación concurrente',
      'Administración de base de datos',
      'Comunicación Interpersonal',
      'Proyecto de Innovación Tecnológica'
    ],
    cycle5: [
      'Diseño gráfico',
      'Animación de gráficos',
      'Herramientas multimedia',
      'Gestión y administración web',
      'Diseño web',
      'Comunicación Empresarial',
      'Ética Profesional',
      'Organización y Constitución de Empresas'
    ],
    cycle6: [
      'Taller de programación web',
      'Comercio Electrónico',
      'Aplicaciones móbiles',
      'Producción audiovisual',
      'Liderazgo y trabajo en Equipo',
      'Proyecto Empresarial',
      'Legislación e Inserción Laboral'
    ]
  },
  {
    slug: '/administracion-de-empresas',
    title: 'ADMINISTRACIÓN DE EMPRESAS',
    imgFront: 'Programs/Front/FrontAdministracion.webp',
    altImgFront: 'Imagen de descripción de la carrera de Administración de Empresas',
    descriptionShort: 'La carrera de Administración de Empresas se enfoca en la gestión eficiente de recursos, toma de decisiones y dirección de organizaciones. Los estudiantes adquieren habilidades en contabilidad, finanzas, marketing y liderazgo, preparándolos para roles en el mundo empresarial.',
    about: '¿QUÉ ES ADMINISTRACIÓN DE EMPRESAS?',
    descriptionAbout1: 'La Administración de Empresas se ocupa de planificar, organizar, dirigir y controlar los recursos de una organización para alcanzar sus objetivos. Incluye la gestión de personas, finanzas, operaciones, marketing y estrategia.',
    descriptionAbout2: 'Los administradores de empresas son fundamentales para el funcionamiento eficiente y exitoso de cualquier organización, ya sea pequeña, mediana o grande, en cualquier sector económico.',
    imgAbout: 'Programs/About/AdministracionAbout.webp',
    altImgAbout: '¿Qué es Administración de Empresas?',
    functions: '¿QUÉ HACE UN TÉCNICO EN ADMINISTRACIÓN DE EMPRESAS?',
    descriptionfunctions1: 'Un técnico en Administración de Empresas ayuda en la gestión diaria de una organización, realizando tareas como contabilidad básica, análisis financiero, planificación estratégica, gestión de recursos humanos y atención al cliente.',
    descriptionfunctions2: 'También puede colaborar en la elaboración de informes, preparación de presupuestos, coordinación de eventos empresariales y aplicación de políticas y procedimientos organizacionales.',
    laborFieldDescription: 'egresado en Administración de Empresas',
    laborFieldItems: [
      ['Administración:', ' Asistente Administrativo'],
      ['Finanzas:', ' Analista Financiero'],
      ['Recursos Humanos:', ' Coordinador de RRHH'],
      ['Marketing:', ' Especialista en Marketing'],
      ['Gestión de Proyectos:', ' Gestor de Proyectos'],
      ['Consultoría Empresarial:', ' Consultor Empresarial']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN ADMINISTRACIÓN DE EMPRESAS?',
    syllabusDescription1: 'La Administración de Empresas incluye el estudio de temas como contabilidad, finanzas, marketing, recursos humanos, operaciones, liderazgo, ética empresarial y estrategia.',
    syllabusDescription2: 'Los estudiantes también aprenden sobre herramientas de gestión empresarial, análisis de mercado, técnicas de negociación, toma de decisiones y resolución de problemas en contextos empresariales.',
    imgSyllabus: 'Programs/Syllabus/SyllabusAdministracion.webp',
    altImgSyllabus: '¿Qué se estudia en Administración de Empresas?',
    cycle1: [
      'Contabilidad Básica',
      'Principios de Administración',
      'Matemáticas Financieras',
      'Fundamentos de Marketing',
      'Comunicación Empresarial',
      'Gestión de Recursos Humanos',
      'Ética Empresarial',
      'Informática Aplicada a la Gestión'
    ],
    cycle2: [
      'Contabilidad de Costos',
      'Finanzas Corporativas',
      'Investigación de Mercados',
      'Gestión de Operaciones',
      'Negociación y Resolución de Conflictos',
      'Desarrollo Organizacional',
      'Planificación Estratégica',
      'Software de Gestión Empresarial'
    ],
    cycle3: [
      'Análisis Financiero',
      'Marketing Digital',
      'Gestión de Proyectos',
      'Derecho Empresarial',
      'Liderazgo y Trabajo en Equipo',
      'Desarrollo Sostenible',
      'Innovación Empresarial',
      'Taller de Emprendimiento'
    ],
    cycle4: [
      'Auditoría Empresarial',
      'Economía Empresarial',
      'Gestión de la Calidad',
      'Emprendimiento Social',
      'Tecnologías de la Información para la Gestión',
      'Responsabilidad Social Corporativa',
      'Prácticas Profesionales',
      'Proyecto de Investigación Empresarial'
    ],
    cycle5: [
      'Marketing Internacional',
      'Logística Empresarial',
      'Estrategias de Ventas',
      'Gestión de la Innovación',
      'Consultoría Empresarial',
      'Ética Profesional',
      'Gestión de Crisis Empresariales',
      'Desarrollo de Habilidades Directivas'
    ],
    cycle6: [
      'Comercio Exterior',
      'Finanzas Internacionales',
      'Gestión del Cambio Organizacional',
      'Dirección Estratégica',
      'Gestión del Talento Humano',
      'Plan de Negocios',
      'Seminario de Titulación'
    ]
  },
  {
    slug: '/contabilidad',
    title: 'CONTABILIDAD',
    imgFront: 'Programs/Front/FrontContabilidad.webp',
    altImgFront: 'Imagen de descripción de la carrera de Contabilidad',
    descriptionShort: 'La carrera de Contabilidad se centra en la recopilación, análisis y registro de información financiera. Los estudiantes adquieren habilidades en contabilidad financiera, costos, impuestos y auditoría, preparándolos para roles en el ámbito contable y financiero.',
    about: '¿QUÉ ES CONTABILIDAD?',
    descriptionAbout1: 'La Contabilidad es el proceso de registrar, clasificar y resumir información financiera para la toma de decisiones. Incluye la preparación de estados financieros, análisis de costos, cálculo de impuestos y evaluación de la situación financiera de una empresa.',
    descriptionAbout2: 'Los contadores desempeñan un papel crucial en la gestión y control de los recursos financieros de una organización, proporcionando información precisa y oportuna para la toma de decisiones estratégicas.',
    imgAbout: 'Programs/About/ContabilidadAbout.webp',
    altImgAbout: '¿Qué es Contabilidad?',
    functions: '¿QUÉ HACE UN TÉCNICO EN CONTABILIDAD?',
    descriptionfunctions1: 'Un técnico en Contabilidad registra transacciones financieras, prepara estados financieros, calcula impuestos, analiza costos y colabora en la elaboración de informes financieros para la dirección de la empresa y las autoridades regulatorias.',
    descriptionfunctions2: 'También puede participar en la auditoría interna o externa, garantizando el cumplimiento de las normas contables y la detección de posibles irregularidades o fraudes.',
    laborFieldDescription: 'egresado en Contabilidad',
    laborFieldItems: [
      ['Contabilidad Financiera:', ' Asistente Contable'],
      ['Costos y Presupuestos:', ' Analista de Costos'],
      ['Auditoría:', ' Auditor Interno'],
      ['Impuestos:', ' Especialista en Impuestos'],
      ['Consultoría Contable:', ' Consultor Contable'],
      ['Finanzas:', ' Analista Financiero']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN CONTABILIDAD?',
    syllabusDescription1: 'La Contabilidad abarca el estudio de principios contables, normativa legal, análisis financiero, costos, impuestos, auditoría y sistemas de información contable.',
    syllabusDescription2: 'Los estudiantes aprenden a aplicar técnicas contables y herramientas informáticas para el registro y procesamiento de información financiera, así como a interpretar y comunicar los resultados de manera efectiva.',
    imgSyllabus: 'Programs/Syllabus/SyllabusContabilidad.webp',
    altImgSyllabus: '¿Qué se estudia en Contabilidad?',
    cycle1: [
      'Principios de Contabilidad',
      'Matemáticas Financieras',
      'Legislación Tributaria',
      'Análisis de Estados Financieros',
      'Costos y Presupuestos',
      'Técnicas Contables',
      'Informática Aplicada a la Contabilidad',
      'Ética Profesional'
    ],
    cycle2: [
      'Contabilidad Avanzada',
      'Auditoría Contable',
      'Impuestos Empresariales',
      'Gestión Financiera',
      'Sistemas de Información Contable',
      'Normativa Contable Internacional',
      'Software Contable',
      'Proceso Contable'
    ],
    cycle3: [
      'Contabilidad de Gestión',
      'Control Interno Contable',
      'Costos para la Toma de Decisiones',
      'Auditoría de Estados Financieros',
      'Finanzas Corporativas',
      'Gestión Presupuestaria',
      'Ética Empresarial',
      'Taller de Investigación Contable'
    ],
    cycle4: [
      'Contabilidad Gubernamental',
      'Consultoría Contable',
      'Peritaje Contable',
      'Gestión Tributaria',
      'Gestión de Riesgos Financieros',
      'Gestión de Proyectos Contables',
      'Prácticas Profesionales',
      'Proyecto de Titulación'
    ],
    cycle5: [
      'Contabilidad Internacional',
      'Análisis Financiero Avanzado',
      'Auditoría Forense',
      'Gestión de Cartera',
      'Estrategias Tributarias',
      'Seminario de Contabilidad',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento Contable'
    ],
    cycle6: [
      'Gestión de la Calidad en Contabilidad',
      'Ética en la Profesión Contable',
      'Asesoría Financiera',
      'Normativa Laboral para Contadores',
      'Desarrollo de Software Contable',
      'Plan de Negocios Contables',
      'Seminario de Ética Profesional'
    ]
  },
  {
    slug: '/electronica',
    title: 'ELECTRÓNICA',
    imgFront: 'Programs/Front/FrontElectronica.webp',
    altImgFront: 'Imagen de descripción de la carrera de Electrónica',
    descriptionShort: 'La carrera de Electrónica se enfoca en el diseño, construcción y mantenimiento de sistemas electrónicos. Los estudiantes adquieren habilidades en electricidad, electrónica analógica y digital, telecomunicaciones y control, preparándolos para roles en el sector tecnológico.',
    about: '¿QUÉ ES ELECTRÓNICA?',
    descriptionAbout1: 'La Electrónica es la rama de la ingeniería que se ocupa del estudio de los circuitos eléctricos que contienen componentes electrónicos. Incluye el diseño, análisis, fabricación y mantenimiento de sistemas electrónicos para diversas aplicaciones.',
    descriptionAbout2: 'Los ingenieros electrónicos son responsables del desarrollo de dispositivos y sistemas que utilizamos en la vida cotidiana, desde teléfonos móviles hasta sistemas de control industrial.',
    imgAbout: 'Programs/About/ElectronicaAbout.webp',
    altImgAbout: '¿Qué es Electrónica?',
    functions: '¿QUÉ HACE UN TÉCNICO EN ELECTRÓNICA?',
    descriptionfunctions1: 'Un técnico en Electrónica colabora en la instalación, configuración y mantenimiento de equipos electrónicos, así como en el diseño y montaje de circuitos eléctricos y electrónicos.',
    descriptionfunctions2: 'También puede realizar pruebas y diagnósticos para identificar y solucionar problemas en sistemas electrónicos, así como participar en el desarrollo de nuevos productos y tecnologías.',
    laborFieldDescription: 'egresado en Electronica',
    laborFieldItems: [
      ['Electrónica Industrial:', ' Técnico en Electrónica Industrial'],
      ['Telecomunicaciones:', ' Técnico en Telecomunicaciones'],
      ['Automatización y Control:', ' Técnico en Automatización y Control'],
      ['Ingeniería Biomédica:', ' Técnico en Ingeniería Biomédica'],
      ['Energías Renovables:', ' Técnico en Energías Renovables'],
      ['Electrónica de Consumo:', ' Técnico en Electrónica de Consumo']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN ELECTRÓNICA?',
    syllabusDescription1: 'La Electrónica abarca el estudio de circuitos eléctricos, componentes electrónicos, sistemas digitales, microcontroladores, telecomunicaciones, control automático y sistemas embebidos.',
    syllabusDescription2: 'Los estudiantes aprenden a diseñar y analizar circuitos, programar dispositivos electrónicos, utilizar herramientas de simulación y medición, así como a aplicar normas y estándares en el desarrollo de proyectos electrónicos.',
    imgSyllabus: 'Programs/Syllabus/SyllabusElectronica.webp',
    altImgSyllabus: '¿Qué se estudia en Electrónica?',
    cycle1: [
      'Electricidad y Magnetismo',
      'Electrónica Básica',
      'Programación Estructurada',
      'Instrumentación Electrónica',
      'Matemáticas Aplicadas',
      'Taller de Circuitos',
      'Comunicación Técnica',
      'Seguridad en el Trabajo'
    ],
    cycle2: [
      'Electrónica Digital',
      'Microcontroladores',
      'Sistemas de Control',
      'Electrónica de Potencia',
      'Redes de Comunicaciones',
      'Taller de Telecomunicaciones',
      'Gestión de Proyectos',
      'Inglés Técnico'
    ],
    cycle3: [
      'Electrónica Analógica',
      'Comunicaciones Digitales',
      'Automatización Industrial',
      'Programación de PLCs',
      'Sistemas Embebidos',
      'Taller de Automatización',
      'Ética Profesional',
      'Prácticas Profesionales'
    ],
    cycle4: [
      'Diseño Electrónico',
      'Robótica',
      'Sistemas de Instrumentación Virtual',
      'Redes Industriales',
      'Tecnologías Inalámbricas',
      'Taller de Robótica',
      'Seminario de Electrónica',
      'Proyecto de Titulación'
    ],
    cycle5: [
      'Electrónica de Potencia Aplicada',
      'Telemedicina',
      'Automatización Residencial',
      'Sistemas de Control de Procesos',
      'Energías Renovables',
      'Seminario de Proyectos',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento Tecnológico'
    ],
    cycle6: [
      'Electrónica de Alta Frecuencia',
      'Internet de las Cosas (IoT)',
      'Control de Calidad en Electrónica',
      'Gestión de la Innovación Tecnológica',
      'Normativa de Seguridad Electrónica',
      'Plan de Negocios Tecnológicos',
      'Seminario de Ética y Responsabilidad Social'
    ]
  },
  {
    slug: '/electrotecnia',
    title: 'ELECTROTECNIA',
    imgFront: 'Programs/Front/FrontElectrotecnia.webp',
    altImgFront: 'Imagen de descripción de la carrera de Electrotecnia',
    descriptionShort: 'La carrera de Electrotecnia se enfoca en el estudio de la generación, transmisión y utilización de la energía eléctrica. Los estudiantes adquieren habilidades en instalaciones eléctricas, automatización, control y mantenimiento, preparándolos para roles en el sector eléctrico.',
    about: '¿QUÉ ES ELECTROTECNIA?',
    descriptionAbout1: 'La Electrotecnia es la disciplina que se ocupa del estudio y aplicación de la electricidad en diversos ámbitos, como la generación, transmisión, distribución y utilización de la energía eléctrica.',
    descriptionAbout2: 'Los técnicos en Electrotecnia son responsables del diseño, instalación, mantenimiento y reparación de sistemas eléctricos en edificaciones, industrias, infraestructuras y equipos electrónicos.',
    imgAbout: 'Programs/About/ElectrotecniaAbout.webp',
    altImgAbout: '¿Qué es Electrotecnia?',
    functions: '¿QUÉ HACE UN TÉCNICO EN ELECTROTECNIA?',
    descriptionfunctions1: 'Un técnico en Electrotecnia realiza tareas como la instalación y mantenimiento de sistemas eléctricos, la lectura e interpretación de planos eléctricos, la configuración de dispositivos de control y la solución de problemas en circuitos eléctricos.',
    descriptionfunctions2: 'También puede colaborar en el diseño de instalaciones eléctricas, la supervisión de proyectos y la aplicación de normas de seguridad eléctrica.',
    laborFieldDescription: 'egresado en Electrotecnia',
    laborFieldItems: [
      ['Instalaciones Eléctricas:', ' Técnico en Instalaciones Eléctricas'],
      ['Automatización Industrial:', ' Técnico en Automatización Industrial'],
      ['Energías Renovables:', ' Técnico en Energías Renovables'],
      ['Control y Mantenimiento:', ' Técnico en Control y Mantenimiento'],
      ['Electricidad Residencial:', ' Técnico en Electricidad Residencial'],
      ['Telecomunicaciones:', ' Técnico en Telecomunicaciones']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN ELECTROTECNIA?',
    syllabusDescription1: 'La Electrotecnia abarca el estudio de principios eléctricos, circuitos eléctricos, máquinas eléctricas, sistemas de control, instalaciones eléctricas, automatización, energías renovables y normativa eléctrica.',
    syllabusDescription2: 'Los estudiantes aprenden a realizar cálculos eléctricos, diseñar instalaciones eléctricas, utilizar herramientas y equipos de medición, aplicar técnicas de automatización y mantener sistemas eléctricos en funcionamiento.',
    imgSyllabus: 'Programs/Syllabus/SyllabusElectrotecnia.webp',
    altImgSyllabus: '¿Qué se estudia en Electrotecnia?',
    cycle1: [
      'Electricidad Básica',
      'Circuitos Eléctricos',
      'Instalaciones Eléctricas Residenciales',
      'Automatización Básica',
      'Máquinas Eléctricas',
      'Seguridad Eléctrica',
      'Herramientas y Equipos Eléctricos',
      'Ética Profesional'
    ],
    cycle2: [
      'Electrónica de Potencia',
      'Control de Procesos',
      'Sistemas de Distribución Eléctrica',
      'Instrumentación y Control',
      'Energías Renovables',
      'Taller de Instalaciones Eléctricas',
      'Gestión de Proyectos',
      'Inglés Técnico'
    ],
    cycle3: [
      'Sistemas de Automatización Industrial',
      'Electrónica Industrial',
      'Mantenimiento Eléctrico',
      'Control Numérico Computarizado (CNC)',
      'Taller de Automatización',
      'Ética Empresarial',
      'Prácticas Profesionales',
      'Taller de Electricidad Residencial'
    ],
    cycle4: [
      'Instalaciones Eléctricas Industriales',
      'Diseño de Circuitos Eléctricos',
      'Robótica Industrial',
      'Gestión del Mantenimiento',
      'Telecomunicaciones',
      'Sistemas de Energía Solar',
      'Proyecto de Titulación',
      'Seminario de Electrotecnia'
    ],
    cycle5: [
      'Automatización Avanzada',
      'Gestión de la Calidad en Instalaciones Eléctricas',
      'Eficiencia Energética',
      'Control de Procesos Industriales',
      'Sistemas de Alimentación Ininterrumpida (UPS)',
      'Seminario de Proyectos',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento en Electrotecnia'
    ],
    cycle6: [
      'Domótica',
      'Telecomunicaciones Industriales',
      'Gestión Ambiental en Instalaciones Eléctricas',
      'Normativa de Seguridad Eléctrica',
      'Gestión de Riesgos Laborales',
      'Plan de Negocios en Electrotecnia',
      'Seminario de Ética Profesional'
    ]
  },
  {
    slug: '/laboratorio',
    title: 'LABORATORIO',
    imgFront: 'Programs/Front/FrontLaboratorio.webp',
    altImgFront: 'Imagen de descripción de la carrera de Laboratorio',
    descriptionShort: 'La carrera de Laboratorio se enfoca en la realización de análisis químicos, biológicos y físicos para la investigación y control de calidad. Los estudiantes adquieren habilidades en técnicas de laboratorio, instrumentación y manejo de muestras, preparándolos para roles en el ámbito científico y de salud.',
    about: '¿QUÉ ES LABORATORIO?',
    descriptionAbout1: 'El Laboratorio es un espacio destinado a la investigación, experimentación y análisis de muestras en diversas áreas, como la química, biología, física, medicina, industria y medio ambiente.',
    descriptionAbout2: 'Los técnicos de laboratorio realizan pruebas, ensayos y estudios para obtener información científica y técnica que contribuye al avance del conocimiento y al control de calidad en distintos sectores.',
    imgAbout: 'Programs/About/LaboratorioAbout.webp',
    altImgAbout: '¿Qué es Laboratorio?',
    functions: '¿QUÉ HACE UN TÉCNICO DE LABORATORIO?',
    descriptionfunctions1: 'Un técnico de laboratorio realiza análisis químicos, biológicos y físicos utilizando equipos de laboratorio especializados. También prepara muestras, registra datos, interpreta resultados y colabora en la elaboración de informes técnicos.',
    descriptionfunctions2: 'Además, puede mantener y calibrar equipos, gestionar inventarios de reactivos y materiales, cumplir con normas de seguridad y calidad, y participar en proyectos de investigación y desarrollo.',
    laborFieldDescription: 'egresado en Laboratorio',
    laborFieldItems: [
      ['Química:', ' Técnico de Laboratorio Químico'],
      ['Biología:', ' Técnico de Laboratorio Biológico'],
      ['Física:', ' Técnico de Laboratorio Físico'],
      ['Microbiología:', ' Técnico de Laboratorio Microbiológico'],
      ['Control de Calidad:', ' Técnico de Control de Calidad'],
      ['Investigación Científica:', ' Técnico de Investigación Científica']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN LABORATORIO?',
    syllabusDescription1: 'La carrera de Laboratorio abarca el estudio de técnicas y metodologías de análisis químicos, biológicos y físicos, así como el manejo de equipos de laboratorio, normas de seguridad, calidad y buenas prácticas de laboratorio.',
    syllabusDescription2: 'Los estudiantes aprenden a identificar, clasificar, manipular y analizar distintos tipos de muestras, así como a interpretar y comunicar resultados de manera precisa y confiable.',
    imgSyllabus: 'Programs/Syllabus/SyllabusLaboratorio.webp',
    altImgSyllabus: '¿Qué se estudia en Laboratorio?',
    cycle1: [
      'Introducción a la Química',
      'Biología Celular',
      'Física General',
      'Técnicas de Laboratorio',
      'Matemáticas Aplicadas',
      'Seguridad y Manejo de Muestras',
      'Ética Profesional',
      'Comunicación Científica'
    ],
    cycle2: [
      'Química Analítica',
      'Microbiología Básica',
      'Física Aplicada',
      'Instrumentación de Laboratorio',
      'Bioquímica',
      'Control de Calidad',
      'Inglés Técnico',
      'Prácticas de Laboratorio'
    ],
    cycle3: [
      'Química Orgánica',
      'Biología Molecular',
      'Análisis de Datos',
      'Técnicas Cromatográficas',
      'Microscopía',
      'Normas de Calidad',
      'Gestión de Residuos',
      'Taller de Investigación'
    ],
    cycle4: [
      'Química Ambiental',
      'Biología Ambiental',
      'Física Cuántica',
      'Muestreo y Preparación de Muestras',
      'Control de Procesos',
      'Normativa de Seguridad',
      'Prácticas Profesionales',
      'Proyecto de Investigación'
    ],
    cycle5: [
      'Toxicología',
      'Biotecnología',
      'Análisis Instrumental',
      'Gestión de Laboratorios',
      'Auditoría de Calidad',
      'Seminario de Investigación',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento Científico'
    ],
    cycle6: [
      'Química Farmacéutica',
      'Biología Molecular Avanzada',
      'Física Nuclear',
      'Calibración de Equipos',
      'Ética en la Investigación Científica',
      'Plan de Negocios en Ciencias',
      'Seminario de Ética Profesional'
    ]
  },
  {
    slug: '/mecanica-automotriz',
    title: 'MECÁNICA AUTOMOTRIZ',
    imgFront: 'Programs/Front/FrontAutomotriz.webp',
    altImgFront: 'Imagen de descripción de la carrera de Mecánica Automotriz',
    descriptionShort: 'La carrera de Mecánica Automotriz se centra en el mantenimiento, reparación y diagnóstico de vehículos automotores. Los estudiantes adquieren habilidades en mecánica, electricidad, electrónica y sistemas de control, preparándolos para roles en el sector automotriz.',
    about: '¿QUÉ ES MECÁNICA AUTOMOTRIZ?',
    descriptionAbout1: 'La Mecánica Automotriz es la disciplina que se encarga del mantenimiento, reparación y diagnóstico de vehículos de motor, como automóviles, camiones y motocicletas.',
    descriptionAbout2: 'Los técnicos en Mecánica Automotriz realizan tareas como el ajuste de motores, reparación de sistemas de frenos, suspensión y dirección, y la identificación y solución de fallas en vehículos.',
    imgAbout: 'Programs/About/AutomotrizAbout.webp',
    altImgAbout: '¿Qué es Mecánica Automotriz?',
    functions: '¿QUÉ HACE UN TÉCNICO EN MECÁNICA AUTOMOTRIZ?',
    descriptionfunctions1: 'Un técnico en Mecánica Automotriz realiza el mantenimiento preventivo y correctivo de vehículos, reemplaza piezas y componentes defectuosos, ajusta sistemas mecánicos y electrónicos, y realiza pruebas de funcionamiento y diagnóstico.',
    descriptionfunctions2: 'También puede colaborar en la instalación de accesorios y sistemas de seguridad, asesorar a clientes sobre el cuidado y mantenimiento de sus vehículos, y participar en equipos de trabajo en talleres mecánicos y concesionarios automotrices.',
    laborFieldDescription: 'egresado en Mecánica Automotriz',
    laborFieldItems: [
      ['Mecánica Automotriz:', ' Técnico en Mecánica Automotriz'],
      ['Electricidad Automotriz:', ' Técnico en Electricidad Automotriz'],
      ['Electrónica Automotriz:', ' Técnico en Electrónica Automotriz'],
      ['Diagnóstico de Vehículos:', ' Técnico en Diagnóstico de Vehículos'],
      ['Reparación de Motores:', ' Técnico en Reparación de Motores'],
      ['Inyección Electrónica:', ' Técnico en Inyección Electrónica']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN MECÁNICA AUTOMOTRIZ?',
    syllabusDescription1: 'La Mecánica Automotriz abarca el estudio de sistemas mecánicos, eléctricos, electrónicos y de control presentes en vehículos de motor. Incluye el aprendizaje de técnicas de diagnóstico, reparación y mantenimiento de automóviles, camiones y motocicletas.',
    syllabusDescription2: 'Los estudiantes aprenden a utilizar herramientas especializadas, equipos de diagnóstico, manuales técnicos y software de gestión para realizar tareas de reparación y servicio en el área automotriz.',
    imgSyllabus: 'Programs/Syllabus/SyllabusAutomotriz.webp',
    altImgSyllabus: '¿Qué se estudia en Mecánica Automotriz?',
    cycle1: [
      'Mecánica Básica',
      'Electricidad del Automóvil',
      'Electrónica del Automóvil',
      'Sistemas de Frenos',
      'Sistemas de Suspensión y Dirección',
      'Motores de Combustión Interna',
      'Taller de Mecánica',
      'Seguridad y Salud Ocupacional'
    ],
    cycle2: [
      'Transmisiones y Embragues',
      'Sistemas de Alimentación de Combustible',
      'Sistemas de Encendido y Arranque',
      'Aire Acondicionado Automotriz',
      'Sistemas de Seguridad Pasiva',
      'Taller de Electricidad y Electrónica',
      'Gestión de Proyectos',
      'Inglés Técnico'
    ],
    cycle3: [
      'Diagnóstico de Fallas',
      'Reparación de Motores',
      'Sistemas de Inyección Electrónica',
      'Cajas de Cambio Automáticas',
      'Sistemas de Control de Emisiones',
      'Taller de Motores',
      'Ética Profesional',
      'Prácticas Profesionales'
    ],
    cycle4: [
      'Reparación de Sistemas Híbridos',
      'Sistemas de Propulsión Eléctrica',
      'Diagnóstico de Sistemas Electrónicos',
      'Suspensión Neumática',
      'Gestión del Mantenimiento Automotriz',
      'Taller de Sistemas de Inyección',
      'Proyecto de Titulación',
      'Seminario de Mecánica Automotriz'
    ],
    cycle5: [
      'Diagnóstico por Escaneo',
      'Sistemas de Navegación y Multimedia',
      'Dinámica del Automóvil',
      'Robótica Aplicada a la Automoción',
      'Normativa Ambiental Automotriz',
      'Seminario de Proyectos',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento en Automoción'
    ],
    cycle6: [
      'Tecnologías Emergentes en Automoción',
      'Sistemas Avanzados de Asistencia al Conductor',
      'Análisis de Accidentes de Tráfico',
      'Gestión de Talleres Mecánicos',
      'Legislación Automotriz',
      'Plan de Negocios en Automoción',
      'Seminario de Ética Profesional'
    ]
  },
  {
    slug: '/mecanica-de-produccion',
    title: 'MECÁNICA DE PRODUCCIÓN',
    imgFront: 'Programs/Front/FrontProduccion.webp',
    altImgFront: 'Imagen de descripción de la carrera de Mecánica de Producción',
    descriptionShort: 'La carrera de Mecánica de Producción se centra en el diseño, fabricación, automatización y control de procesos industriales. Los estudiantes adquieren habilidades en maquinaria, herramientas, técnicas de producción y gestión de calidad, preparándolos para roles en la industria manufacturera.',
    about: '¿QUÉ ES MECÁNICA DE PRODUCCIÓN?',
    descriptionAbout1: 'La Mecánica de Producción es una disciplina que se enfoca en el diseño, desarrollo y optimización de procesos de fabricación en la industria. Incluye el estudio de máquinas, herramientas, materiales, métodos de producción y sistemas de control.',
    descriptionAbout2: 'Los técnicos en Mecánica de Producción son responsables de planificar, implementar y mejorar procesos productivos, garantizando la eficiencia, calidad y seguridad en la manufactura de bienes y productos.',
    imgAbout: 'Programs/About/ProduccionAbout.webp',
    altImgAbout: '¿Qué es Mecánica de Producción?',
    functions: '¿QUÉ HACE UN TÉCNICO EN MECÁNICA DE PRODUCCIÓN?',
    descriptionfunctions1: 'Un técnico en Mecánica de Producción participa en el diseño y desarrollo de productos, selecciona y configura maquinaria y equipos industriales, implementa sistemas de control de calidad y supervisa la producción en plantas fabriles.',
    descriptionfunctions2: 'También puede realizar mantenimiento preventivo y correctivo de maquinaria, gestionar inventarios de materiales y herramientas, optimizar procesos productivos y colaborar en proyectos de mejora continua.',
    laborFieldDescription: 'Área y cargo:',
    laborFieldItems: [
      ['Procesos de Producción:', ' Técnico en Procesos de Producción'],
      ['Diseño y Fabricación:', ' Técnico en Diseño y Fabricación'],
      ['Control de Calidad:', ' Técnico en Control de Calidad'],
      ['Mantenimiento Industrial:', ' Técnico en Mantenimiento Industrial'],
      ['Automatización de Procesos:', ' Técnico en Automatización de Procesos'],
      ['Lean Manufacturing:', ' Técnico en Lean Manufacturing']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN MECÁNICA DE PRODUCCIÓN?',
    syllabusDescription1: 'La Mecánica de Producción abarca el estudio de procesos de fabricación, métodos de mecanizado, tecnologías de producción, sistemas de control industrial, gestión de la calidad y mejora continua en la industria manufacturera.',
    syllabusDescription2: 'Los estudiantes aprenden a utilizar herramientas CAD/CAM, máquinas CNC, sistemas de gestión de la producción, técnicas de control estadístico de calidad y metodologías como Lean Manufacturing y Six Sigma.',
    imgSyllabus: 'Programs/Syllabus/SyllabusProduccion.webp',
    altImgSyllabus: '¿Qué se estudia en Mecánica de Producción?',
    cycle1: [
      'Dibujo Técnico',
      'Mecánica Básica',
      'Tecnología de Materiales',
      'Procesos de Manufactura',
      'Control de Calidad',
      'Seguridad Industrial',
      'Herramientas y Máquinas',
      'Ética Profesional'
    ],
    cycle2: [
      'Diseño Asistido por Computadora (CAD)',
      'Manufactura Asistida por Computadora (CAM)',
      'Metrología',
      'Automatización Industrial',
      'Gestión de Inventarios',
      'Taller de Producción',
      'Gestión de Proyectos',
      'Inglés Técnico'
    ],
    cycle3: [
      'Máquinas Herramienta',
      'Control Numérico Computarizado (CNC)',
      'Control Estadístico de Procesos (SPC)',
      'Lean Manufacturing',
      'Taller de CNC',
      'Gestión de Calidad Total (TQM)',
      'Ética Empresarial',
      'Prácticas Profesionales'
    ],
    cycle4: [
      'Diseño para la Manufactura (DFM)',
      'Sistemas de Producción Flexible',
      'Six Sigma',
      'Gestión de Mantenimiento',
      'Simulación de Procesos',
      'Taller de Producción Avanzada',
      'Proyecto de Titulación',
      'Seminario de Mecánica de Producción'
    ],
    cycle5: [
      'Ingeniería Concurrente',
      'Gestión de la Innovación',
      'Gestión Ambiental en la Producción',
      'Optimización de Procesos',
      'Gestión de Costos',
      'Seminario de Proyectos',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento Industrial'
    ],
    cycle6: [
      'Gestión de la Cadena de Suministro',
      'Producción Justo a Tiempo (JIT)',
      'Ergonomía y Diseño del Trabajo',
      'Robótica Industrial',
      'Gestión de Riesgos',
      'Plan de Negocios en Producción',
      'Seminario de Ética Profesional'
    ]
  },
  {
    slug: '/metalurgia',
    title: 'METALURGIA',
    imgFront: 'Programs/Front/FrontMetalurgia.webp',
    altImgFront: 'Imagen de descripción de la carrera de Metalurgia',
    descriptionShort: 'La carrera de Metalurgia se enfoca en el estudio y procesamiento de metales y aleaciones para la producción de materiales metálicos. Los estudiantes adquieren habilidades en fundición, forja, soldadura, tratamiento térmico y control de calidad, preparándolos para roles en la industria metalúrgica.',
    about: '¿QUÉ ES METALURGIA?',
    descriptionAbout1: 'La Metalurgia es la ciencia y técnica relacionada con la extracción, refinación, procesamiento y producción de metales y aleaciones. Incluye el estudio de propiedades físicas, químicas y mecánicas de los materiales metálicos.',
    descriptionAbout2: 'Los técnicos en Metalurgia trabajan en la transformación de minerales en metales útiles, el diseño y producción de aleaciones, y el control de calidad en la fabricación de productos metálicos para diversas industrias.',
    imgAbout: 'Programs/About/MetalurgiaAbout.webp',
    altImgAbout: '¿Qué es Metalurgia?',
    functions: '¿QUÉ HACE UN TÉCNICO EN METALURGIA?',
    descriptionfunctions1: 'Un técnico en Metalurgia participa en la extracción y procesamiento de minerales metálicos, la fundición de metales, la fabricación de aleaciones, el tratamiento térmico, la soldadura y el control de calidad en la producción de materiales metálicos.',
    descriptionfunctions2: 'También puede realizar análisis metalográficos, ensayos de materiales, diseño de procesos metalúrgicos, gestión de residuos industriales y colaborar en proyectos de investigación y desarrollo.',
    laborFieldDescription: 'Área y cargo:',
    laborFieldItems: [
      ['Fundición:', ' Técnico en Fundición'],
      ['Forja y Estampado:', ' Técnico en Forja y Estampado'],
      ['Soldadura y Ensamblaje:', ' Técnico en Soldadura y Ensamblaje'],
      ['Tratamientos Térmicos:', ' Técnico en Tratamientos Térmicos'],
      ['Control de Calidad Metalúrgica:', ' Técnico en Control de Calidad Metalúrgica'],
      ['Ingeniería de Materiales:', ' Técnico en Ingeniería de Materiales']
    ],
    syllabus: '¿QUÉ SE ESTUDIA EN METALURGIA?',
    syllabusDescription1: 'La Metalurgia abarca el estudio de procesos de extracción, refinación, conformado, tratamiento térmico, soldadura y control de calidad de metales y aleaciones. Incluye el análisis de estructuras cristalinas y propiedades mecánicas de los materiales metálicos.',
    syllabusDescription2: 'Los estudiantes aprenden a utilizar técnicas metalúrgicas, equipos de laboratorio, normativas de seguridad, software de simulación y herramientas de caracterización de materiales para el desarrollo y mejora de productos metálicos.',
    imgSyllabus: 'Programs/Syllabus/SyllabusMetalurgia.webp',
    altImgSyllabus: '¿Qué se estudia en Metalurgia?',
    cycle1: [
      'Química General',
      'Física General',
      'Tecnología de Materiales',
      'Procesos Metalúrgicos',
      'Seguridad Industrial',
      'Herramientas de Laboratorio',
      'Ética Profesional',
      'Comunicación Técnica'
    ],
    cycle2: [
      'Mineralogía y Petrología',
      'Metalurgia Extractiva',
      'Diagramas de Equilibrio',
      'Fundición de Metales',
      'Soldadura y Ensamblaje',
      'Pruebas No Destructivas',
      'Gestión Ambiental',
      'Inglés Técnico'
    ],
    cycle3: [
      'Metalurgia Física',
      'Metalurgia Mecánica',
      'Tratamientos Térmicos',
      'Forja y Estampado',
      'Análisis Metalográfico',
      'Gestión de Calidad',
      'Ética Empresarial',
      'Prácticas Profesionales'
    ],
    cycle4: [
      'Aleaciones Metálicas',
      'Corrosión y Protección',
      'Diseño de Experimentos',
      'Simulación Metalúrgica',
      'Normativas y Certificaciones',
      'Prácticas de Laboratorio',
      'Proyecto de Investigación',
      'Seminario de Metalurgia'
    ],
    cycle5: [
      'Caracterización de Materiales',
      'Diseño de Procesos',
      'Ingeniería de Superficies',
      'Gestión de Residuos',
      'Optimización de Costos',
      'Seminario de Proyectos',
      'Desarrollo de Habilidades Gerenciales',
      'Emprendimiento en Metalurgia'
    ],
    cycle6: [
      'Tecnologías Emergentes en Metalurgia',
      'Innovación en Productos',
      'Gestión de la Producción',
      'Reciclaje de Metales',
      'Gestión de Riesgos',
      'Plan de Negocios en Metalurgia',
      'Seminario de Ética Profesional'
    ]
  }
]
