export interface PROGRAM {
  slug : string,
  title : string,
  imgFront: string,
  altImgFront: string,
  descriptionShort : string,
  about : string,
  descriptionAbout1 : string,
  descriptionAbout2 : string,
  imgAbout: string,
  altImgAbout: string,
  functions : string,
  descriptionfunctions1 : string,
  descriptionfunctions2 : string,
  laborFieldDescription: string,
  laborFieldItems : string[][],
  syllabus : string,
  syllabusDescription1 : string,
  syllabusDescription2 : string,
  imgSyllabus: string,
  altImgSyllabus: string,
  cycle1 : string[],
  cycle2 : string[],
  cycle3 : string[],
  cycle4 : string[],
  cycle5 : string[],
  cycle6 : string[],
}